### ISSUE TITLE
Tracker is not working on Tibia 10.75

### ISSUE THREAD

**Issue by tuliomagalhaes** [jo3bingham/sharpmaptracker#3]
I'm trying to compile and run using a 10.75 client, but it's not working. The items.otb and the client loads ok, but when I do login, it doesn't work.

OBS: I'm trying in otservers.

**Comment by Schiffers** [comment]
not work for otservers, did you never see it in otland ? they remove this function of tracker maps from otserver bacause the owners of otservers ask for it, to be original his maps

**Comment by tuliomagalhaes** [comment]
Solved, thanks.
Em 24/04/2015 05:40, "Schiffers" notifications@github.com escreveu:
